### PR TITLE
Add per-component throughput and unavailability of information

### LINKED ISSUE #14: Add component throughput
We have node power, node throughput.

We have component power, but not component throughput.

Not only is this inconsistent but the same logic applies: whatever can be calculated for the node using node power and node throughput can be calculated for a component if we have both.

### PR DESCRIPTION
**Pull request by mwelzl**
Closes #14

### CODE REVIEW

**Review by cpignata — APPROVED** [review]
Super Nice!
Do we need to add an Informational Reference to UUID?

**Comment by jmparikh** [comment]
Good catch on the "length field for no payload available".

**Comment by mwelzl** [comment]
> Super Nice! Do we need to add an Informational Reference to UUID?

Thanks!  Reference - I don't know?  but that can be done in a separate PR.  Since you like this one, I'm merging it  :-)  and doing the other tomorrow!

**Comment by cpignata** [comment]
Yes, I’d add an Informational reference to rfc4122

**Pull request merged**
